"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa

${imports if imports else ""}

def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    ${upgrades if upgrades else "pass"}
    ### end Alembic commands ###


def downgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    ${downgrades if downgrades else "pass"}
    ### end Alembic commands ### 