"""add user fields

Revision ID: e26809aecbf9
Revises: c12d2e2a11a6
Create Date: 2025-04-19 14:01:51.722920

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e26809aecbf9'
down_revision = 'c12d2e2a11a6'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
