"""add gender and dob fields

Revision ID: ed88d29435ad
Revises: e26809aecbf9
Create Date: 2025-04-19 14:02:41.560605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed88d29435ad'
down_revision = 'e26809aecbf9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Gender and date_of_birth columns already exist
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes to revert
    pass
    # ### end Alembic commands ###
